version: ${DOCKER_VERSION}

services:
  # Database
  db:
    container_name: ${DOCKER_NETWORK_NAME}_${DOCKER_MYSQL_CONTAINER_NAME}
    image: ${DOCKER_MYSQL_IMAGE}
    volumes:
      - db_data:/var/lib/mysql
    restart: always #If the server reboots so will the container
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_MYSQL_DATABASE}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASSWORD}
    networks:
      - mynetwork
  # phpmyadmin
  phpmyadmin:
    container_name: ${DOCKER_NETWORK_NAME}_${DOCKER_PHPMYADMIN_CONTAINER_NAME}
    depends_on:
      - db
    image: ${DOCKER_PHPMYADMIN_IMAGE}
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT_PASSWORD}
    networks:
      - mynetwork
  # Wordpress
  wordpress:
    container_name: ${DOCKER_NETWORK_NAME}_${DOCKER_WORDPRESS_CONTAINER_NAME}
    depends_on:
      - db
    image: jameswordpress
    build: .
    ports:
      - '8000:80'
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content/
    environment:
      WORDPRESS_DB_HOST: ${DOCKER_WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${DOCKER_WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${DOCKER_WORDPRESS_DB_PASSWORD}
    networks:
      - mynetwork
networks:
  mynetwork:
    name: ${DOCKER_NETWORK_NAME}
volumes:
  db_data: